### ISSUE TITLE
once started, the streaminggui.py raises exception

### ISSUE THREAD

**Issue by camillerougier** [Wisear/BLE-catie#4]
environment : linux mint
setup : no catie board on

when no board is connected, the streaming starts anyway but exception occurs

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
start_streaming
None
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "streaming_gui.py", line 114, in start_loop
    loop_.run_until_complete(start_streaming(self, new_filename, verbose=True))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "streaming_gui.py", line 54, in start_streaming
    async with client:
  File "/usr/local/lib/python3.8/dist-packages/bleak/backends/client.py", line 61, in __aenter__
    await self.connect()
  File "/usr/local/lib/python3.8/dist-packages/bleak/backends/bluezdbus/client.py", line 112, in connect
    device = await BleakScannerBlueZDBus.find_device_by_address(
  File "/usr/local/lib/python3.8/dist-packages/bleak/backends/scanner.py", line 203, in find_device_by_address
    device_identifier = device_identifier.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
start_streaming
None

**Comment by antoine-lebaud** [comment]
En effet, mon code n'est pas (encore robuste) au cas d'usage où la streaming est lancé sans une board allumée. Il faut que je réfléchis à une solution asap.
